// Generated by sources/build_db.py from sources/os_czasu.txt - do not edit by hand.
// Anchor dates for the study screen; everything else hangs off them.
const dateTimeline = [
  {
    "year": 966,
    "title": "Chrzest Polski",
    "role": "Początki państwa",
    "note": "Mieszko I przyjmuje chrzest. Od tej daty liczy się istnienie państwa polskiego w chrześcijańskiej Europie.",
    "hooks": [
      "Tysiąclecie chrztu Polski obchodzono w 1966 r. - te same trzy cyfry, tysiąc lat później.",
      "Pierwsza epoka to Piastowie: od Mieszka I (966) do zjednoczenia przez Łokietka (1320)."
    ],
    "events": [
      {
        "year": 965,
        "title": "Ślub Mieszka I z Dobrawą",
        "note": "Czeska księżniczka; małżeństwo przygotowało grunt pod chrzest rok później.",
        "core": false
      },
      {
        "year": 966,
        "title": "Chrzest Polski",
        "note": "Mieszko I przyjmuje chrzest z Czech, omijając zależność od cesarstwa niemieckiego.",
        "core": true
      },
      {
        "year": 968,
        "title": "Pierwsze biskupstwo w Poznaniu",
        "note": "Biskup Jordan, początek organizacji kościelnej w Polsce.",
        "core": false
      },
      {
        "year": 972,
        "title": "Bitwa pod Cedynią",
        "note": "Mieszko I pokonuje margrabiego Hodona, pierwsze znane zwycięstwo polskiego oręża.",
        "core": false
      },
      {
        "year": 991,
        "title": "Dagome iudex",
        "note": "Mieszko oddaje państwo pod opiekę papieża - najstarszy opis granic Polski.",
        "core": false
      },
      {
        "year": 992,
        "title": "Śmierć Mieszka I",
        "note": "Władzę przejmuje jego syn Bolesław Chrobry.",
        "core": false
      },
      {
        "year": 997,
        "title": "Męczeństwo św. Wojciecha",
        "note": "Zginął podczas misji wśród Prusów. Jego grób w Gnieźnie stał się powodem zjazdu w 1000 r.",
        "core": true
      },
      {
        "year": 1000,
        "title": "Zjazd gnieźnieński",
        "note": "Cesarz Otton III przybywa do grobu św. Wojciecha. Powstaje pierwsza polska metropolia kościelna.",
        "core": true
      },
      {
        "year": 1025,
        "title": "Koronacja Bolesława Chrobrego",
        "note": "Pierwszy koronowany król Polski; koronacja odbyła się w roku jego śmierci.",
        "core": true
      },
      {
        "year": 1039,
        "title": "Kazimierz Odnowiciel przenosi stolicę do Krakowa",
        "note": "Gniezno zniszczone przez najazd czeski; Kraków stolicą na następne 500 lat.",
        "core": false
      },
      {
        "year": 1076,
        "title": "Koronacja Bolesława Śmiałego",
        "note": "Odnowienie królestwa po okresie kryzysu.",
        "core": false
      },
      {
        "year": 1079,
        "title": "Zabójstwo biskupa Stanisława",
        "note": "Konflikt króla z biskupem krakowskim; św. Stanisław to jeden z patronów Polski.",
        "core": false
      },
      {
        "year": 1109,
        "title": "Obrona Głogowa i bitwa na Psim Polu",
        "note": "Bolesław Krzywousty odpiera najazd cesarza Henryka V.",
        "core": false
      },
      {
        "year": 1138,
        "title": "Testament Bolesława Krzywoustego",
        "note": "Podział państwa między synów. Początek rozbicia dzielnicowego na prawie 200 lat.",
        "core": true
      },
      {
        "year": 1226,
        "title": "Konrad Mazowiecki sprowadza Krzyżaków",
        "note": "Zaprosił zakon do walki z Prusami. Z pomocnika wyrósł najgroźniejszy wróg.",
        "core": true
      },
      {
        "year": 1241,
        "title": "Najazd Mongołów i bitwa pod Legnicą",
        "note": "Ginie Henryk Pobożny; Mongołowie pustoszą południe Polski.",
        "core": true
      },
      {
        "year": 1320,
        "title": "Koronacja Władysława Łokietka",
        "note": "Koniec rozbicia dzielnicowego, państwo znów zjednoczone.",
        "core": true
      }
    ]
  },
  {
    "year": 1410,
    "title": "Bitwa pod Grunwaldem",
    "role": "Szczyt potęgi",
    "note": "15 lipca. Wojska polsko-litewskie pod wodzą Władysława Jagiełły rozbijają zakon krzyżacki. Jedna z największych bitew średniowiecznej Europy.",
    "hooks": [
      "Łańcuch przyczyn i skutków: 1226 sprowadzenie Krzyżaków - 1410 Grunwald - 1466 odzyskanie Pomorza - 1525 hołd pruski.",
      "Kazimierz Wielki: 1333-1370. \"Zastał Polskę drewnianą, a zostawił murowaną\"."
    ],
    "events": [
      {
        "year": 1333,
        "title": "Początek panowania Kazimierza Wielkiego",
        "note": "Ostatni król z dynastii Piastów, wielki budowniczy i reformator.",
        "core": true
      },
      {
        "year": 1343,
        "title": "Pokój kaliski",
        "note": "Kazimierz Wielki kończy spór z Krzyżakami, odzyskuje Kujawy.",
        "core": false
      },
      {
        "year": 1364,
        "title": "Akademia Krakowska",
        "note": "Kazimierz Wielki zakłada pierwszy polski uniwersytet, dziś Uniwersytet Jagielloński.",
        "core": true
      },
      {
        "year": 1370,
        "title": "Śmierć Kazimierza Wielkiego",
        "note": "Koniec dynastii Piastów na polskim tronie.",
        "core": true
      },
      {
        "year": 1384,
        "title": "Koronacja Jadwigi",
        "note": "Dziesięcioletnia Jadwiga zostaje \"królem\" Polski; później święta patronka.",
        "core": false
      },
      {
        "year": 1385,
        "title": "Unia w Krewie",
        "note": "Umowa Polski z Litwą: Jagiełło przyjmuje chrzest i rękę Jadwigi. Początek dynastii Jagiellonów.",
        "core": true
      },
      {
        "year": 1386,
        "title": "Chrzest i koronacja Władysława Jagiełły",
        "note": "Litwa przyjmuje chrześcijaństwo, Jagiełło zostaje królem Polski.",
        "core": false
      },
      {
        "year": 1410,
        "title": "Bitwa pod Grunwaldem",
        "note": "Największe zwycięstwo nad zakonem krzyżackim; dowodził Władysław Jagiełło.",
        "core": true
      },
      {
        "year": 1411,
        "title": "Pierwszy pokój toruński",
        "note": "Kończy wojnę z Krzyżakami, ale bez wielkich zdobyczy terytorialnych.",
        "core": false
      },
      {
        "year": 1444,
        "title": "Bitwa pod Warną",
        "note": "Ginie młody król Władysław III, odtąd zwany Warneńczykiem.",
        "core": true
      },
      {
        "year": 1454,
        "title": "Początek wojny trzynastoletniej",
        "note": "Wojna z Krzyżakami o Pomorze, trwa do 1466 r.",
        "core": false
      },
      {
        "year": 1466,
        "title": "Drugi pokój toruński",
        "note": "Pomorze Gdańskie z Malborkiem wraca do Polski; Prusy Zakonne lennem.",
        "core": true
      },
      {
        "year": 1473,
        "title": "Narodziny Mikołaja Kopernika",
        "note": "Urodzony w Toruniu; twórca teorii heliocentrycznej.",
        "core": true
      },
      {
        "year": 1493,
        "title": "Pierwszy sejm walny w Piotrkowie",
        "note": "Początek polskiego parlamentaryzmu dwuizbowego.",
        "core": false
      }
    ]
  },
  {
    "year": 1569,
    "title": "Unia Lubelska",
    "role": "Rzeczpospolita Obojga Narodów",
    "note": "Polska i Litwa łączą się w jedno państwo ze wspólnym sejmem i wspólnym królem. Powstaje jedno z największych państw ówczesnej Europy.",
    "hooks": [
      "Cały wiek XVI to Złoty Wiek - unia wypada dokładnie w jego drugiej połowie.",
      "Po 1573 r. króla wybierano w wolnej elekcji - to odróżnia Polskę od reszty Europy."
    ],
    "events": [
      {
        "year": 1505,
        "title": "Konstytucja Nihil novi",
        "note": "\"Nic o nas bez nas\" - król nie może stanowić prawa bez zgody sejmu.",
        "core": false
      },
      {
        "year": 1525,
        "title": "Hołd pruski",
        "note": "Albrecht Hohenzollern klęka przed Zygmuntem I Starym na rynku w Krakowie.",
        "core": true
      },
      {
        "year": 1543,
        "title": "Dzieło Kopernika",
        "note": "\"O obrotach sfer niebieskich\" ukazuje się w roku śmierci astronoma.",
        "core": true
      },
      {
        "year": 1569,
        "title": "Unia Lubelska",
        "note": "Powstaje Rzeczpospolita Obojga Narodów - jedno państwo Polski i Litwy.",
        "core": true
      },
      {
        "year": 1572,
        "title": "Śmierć Zygmunta II Augusta",
        "note": "Koniec dynastii Jagiellonów; początek królów elekcyjnych.",
        "core": true
      },
      {
        "year": 1573,
        "title": "Konfederacja warszawska i pierwsza wolna elekcja",
        "note": "Gwarancja tolerancji religijnej; królem wybrany Henryk Walezy.",
        "core": true
      },
      {
        "year": 1596,
        "title": "Przeniesienie stolicy do Warszawy",
        "note": "Zygmunt III Waza przenosi dwór z Krakowa; Warszawa stolicą do dziś.",
        "core": true
      },
      {
        "year": 1605,
        "title": "Bitwa pod Kircholmem",
        "note": "Husaria Chodkiewicza rozbija czterokrotnie liczniejszych Szwedów.",
        "core": false
      },
      {
        "year": 1610,
        "title": "Bitwa pod Kłuszynem",
        "note": "Polacy zajmują Moskwę - jedyny taki epizod w historii.",
        "core": false
      },
      {
        "year": 1648,
        "title": "Powstanie Chmielnickiego",
        "note": "Wielkie powstanie kozackie, początek upadku Rzeczypospolitej.",
        "core": false
      },
      {
        "year": 1655,
        "title": "Potop szwedzki",
        "note": "Najazd Szwecji trwa do 1660 r. Obrona Jasnej Góry pod wodzą przeora Augustyna Kordeckiego.",
        "core": true
      },
      {
        "year": 1656,
        "title": "Śluby lwowskie Jana Kazimierza",
        "note": "Król ogłasza Matkę Bożą Królową Polski.",
        "core": false
      },
      {
        "year": 1683,
        "title": "Odsiecz wiedeńska",
        "note": "Jan III Sobieski rozbija Turków pod Wiedniem i ratuje Europę.",
        "core": true
      }
    ]
  },
  {
    "year": 1795,
    "title": "III rozbiór Polski",
    "role": "Koniec państwa",
    "note": "Rosja, Prusy i Austria dzielą resztę Rzeczypospolitej. Polska znika z mapy Europy na 123 lata.",
    "hooks": [
      "1795 + 123 lata zaborów = 1918. Znasz jedną datę - wyliczasz drugą.",
      "Trzy daty tego bloku są nieparzyste i idą co dwa lata: 1791 Konstytucja, 1793 II rozbiór, 1795 III rozbiór.",
      "Powstania: 1794 Kościuszko, 1830 listopadowe, 1863 styczniowe. Co mniej więcej 33 lata."
    ],
    "events": [
      {
        "year": 1764,
        "title": "Koronacja Stanisława Augusta Poniatowskiego",
        "note": "Ostatni król Polski, mecenas kultury i oświaty.",
        "core": false
      },
      {
        "year": 1772,
        "title": "I rozbiór Polski",
        "note": "Pierwszy podział ziem Rzeczypospolitej między Rosję, Prusy i Austrię.",
        "core": true
      },
      {
        "year": 1773,
        "title": "Komisja Edukacji Narodowej",
        "note": "Pierwsze na świecie ministerstwo oświaty.",
        "core": false
      },
      {
        "year": 1791,
        "title": "Konstytucja 3 Maja",
        "note": "Pierwsza konstytucja w Europie, druga na świecie. Próba ratowania państwa.",
        "core": true
      },
      {
        "year": 1793,
        "title": "II rozbiór Polski",
        "note": "Odpowiedź sąsiadów na Konstytucję 3 Maja, zaledwie dwa lata po niej.",
        "core": true
      },
      {
        "year": 1794,
        "title": "Insurekcja kościuszkowska",
        "note": "Powstanie pod wodzą Tadeusza Kościuszki; bitwa pod Racławicami z kosynierami.",
        "core": true
      },
      {
        "year": 1795,
        "title": "III rozbiór Polski",
        "note": "Polska znika z mapy Europy na 123 lata.",
        "core": true
      },
      {
        "year": 1797,
        "title": "Mazurek Dąbrowskiego",
        "note": "Józef Wybicki pisze go we Włoszech dla Legionów. Hymn powstaje, gdy państwa już nie ma.",
        "core": true
      },
      {
        "year": 1807,
        "title": "Księstwo Warszawskie",
        "note": "Namiastka państwa utworzona przez Napoleona; przetrwała do 1815 r.",
        "core": false
      },
      {
        "year": 1815,
        "title": "Kongres wiedeński",
        "note": "Nowy podział ziem polskich; powstaje Królestwo Polskie zależne od Rosji.",
        "core": false
      },
      {
        "year": 1830,
        "title": "Powstanie listopadowe",
        "note": "Wybucha 29 listopada w Warszawie, przeciw Rosji.",
        "core": true
      },
      {
        "year": 1846,
        "title": "Powstanie krakowskie i rabacja galicyjska",
        "note": "Nieudany zryw, tragicznie zakończony wystąpieniem chłopów.",
        "core": false
      },
      {
        "year": 1848,
        "title": "Wiosna Ludów",
        "note": "Polacy walczą o wolność w wielu krajach Europy.",
        "core": false
      },
      {
        "year": 1863,
        "title": "Powstanie styczniowe",
        "note": "Wybucha 22 stycznia, największe polskie powstanie narodowe; ostatni dyktator Romuald Traugutt.",
        "core": true
      },
      {
        "year": 1864,
        "title": "Uwłaszczenie chłopów",
        "note": "Reforma w Królestwie Polskim po upadku powstania styczniowego.",
        "core": false
      }
    ]
  },
  {
    "year": 1918,
    "title": "Odzyskanie niepodległości",
    "role": "Odrodzenie",
    "note": "11 listopada. Po 123 latach zaborów Polska wraca na mapę Europy. Józef Piłsudski obejmuje władzę.",
    "hooks": [
      "1918 to koniec I wojny światowej - tej daty nie zapomnisz, a od niej wyliczysz 1795.",
      "Od niepodległości do wybuchu wojny mija 21 lat: 1918-1939. Cała II Rzeczpospolita to jedno pokolenie."
    ],
    "events": [
      {
        "year": 1903,
        "title": "Nobel dla Marii Skłodowskiej-Curie",
        "note": "Nagroda z fizyki; w 1911 r. otrzyma drugą, z chemii.",
        "core": true
      },
      {
        "year": 1905,
        "title": "Nobel dla Henryka Sienkiewicza",
        "note": "Pierwszy polski noblista z literatury.",
        "core": true
      },
      {
        "year": 1911,
        "title": "Drugi Nobel dla Skłodowskiej-Curie",
        "note": "Z chemii; jedyna kobieta z Noblami w dwóch dziedzinach nauki.",
        "core": true
      },
      {
        "year": 1914,
        "title": "Wybuch I wojny światowej",
        "note": "Zaborcy stają po przeciwnych stronach - szansa dla sprawy polskiej.",
        "core": true
      },
      {
        "year": 1918,
        "title": "Odzyskanie niepodległości",
        "note": "11 listopada, po 123 latach zaborów.",
        "core": true
      },
      {
        "year": 1918,
        "title": "Powstanie wielkopolskie",
        "note": "Wybucha 27 grudnia w Poznaniu; jedyne w pełni zwycięskie polskie powstanie.",
        "core": true
      },
      {
        "year": 1919,
        "title": "Powstania śląskie",
        "note": "Trzy zrywy w latach 1919, 1920 i 1921 o przyłączenie Górnego Śląska do Polski.",
        "core": false
      },
      {
        "year": 1920,
        "title": "Bitwa Warszawska",
        "note": "\"Cud nad Wisłą\", 15 sierpnia. Zatrzymanie ofensywy bolszewickiej.",
        "core": true
      },
      {
        "year": 1921,
        "title": "Konstytucja marcowa i pokój ryski",
        "note": "Ustrój II RP i granica wschodnia po wojnie z bolszewikami.",
        "core": false
      },
      {
        "year": 1922,
        "title": "Gabriel Narutowicz pierwszym prezydentem",
        "note": "Zamordowany kilka dni po zaprzysiężeniu.",
        "core": false
      },
      {
        "year": 1924,
        "title": "Nobel dla Władysława Reymonta",
        "note": "Za powieść \"Chłopi\".",
        "core": true
      },
      {
        "year": 1926,
        "title": "Przewrót majowy",
        "note": "Piłsudski przejmuje władzę siłą; początek rządów sanacji.",
        "core": false
      },
      {
        "year": 1932,
        "title": "Złamanie szyfru Enigmy",
        "note": "Marian Rejewski, Jerzy Różycki i Henryk Zygalski.",
        "core": true
      },
      {
        "year": 1935,
        "title": "Konstytucja kwietniowa i śmierć Piłsudskiego",
        "note": "Marszałek umiera 12 maja, pochowany na Wawelu.",
        "core": false
      }
    ]
  },
  {
    "year": 1939,
    "title": "Wybuch II wojny światowej",
    "role": "Katastrofa",
    "note": "1 września Niemcy atakują Polskę - zaczyna się II wojna światowa. 17 września od wschodu wkracza ZSRR.",
    "hooks": [
      "Kolejność jest kluczowa: 23 sierpnia pakt Ribbentrop-Mołotow, 1 września Niemcy, 17 września ZSRR.",
      "Powstania w Warszawie to dwie różne daty: 1943 w getcie, 1944 Powstanie Warszawskie."
    ],
    "events": [
      {
        "year": 1939,
        "title": "Pakt Ribbentrop-Mołotow",
        "note": "23 sierpnia. Tajny podział Polski między III Rzeszę i ZSRR.",
        "core": true
      },
      {
        "year": 1939,
        "title": "Atak Niemiec na Polskę",
        "note": "1 września, Westerplatte. Początek II wojny światowej.",
        "core": true
      },
      {
        "year": 1939,
        "title": "Agresja ZSRR na Polskę",
        "note": "17 września, cios w plecy walczącej Polsce.",
        "core": true
      },
      {
        "year": 1940,
        "title": "Zbrodnia katyńska",
        "note": "NKWD morduje wiosną blisko 22 tysiące polskich oficerów i policjantów.",
        "core": true
      },
      {
        "year": 1940,
        "title": "Pierwszy transport do Auschwitz",
        "note": "14 czerwca, 728 polskich więźniów politycznych z Tarnowa.",
        "core": false
      },
      {
        "year": 1942,
        "title": "Powstanie \"Żegoty\"",
        "note": "Rada Pomocy Żydom, jedyna taka instytucja państwowa w okupowanej Europie.",
        "core": false
      },
      {
        "year": 1943,
        "title": "Powstanie w getcie warszawskim",
        "note": "Wybucha 19 kwietnia, pierwsze powstanie miejskie w okupowanej Europie.",
        "core": true
      },
      {
        "year": 1943,
        "title": "Śmierć gen. Władysława Sikorskiego",
        "note": "4 lipca, katastrofa lotnicza w Gibraltarze.",
        "core": true
      },
      {
        "year": 1944,
        "title": "Powstanie Warszawskie",
        "note": "Wybucha 1 sierpnia i trwa 63 dni.",
        "core": true
      },
      {
        "year": 1945,
        "title": "Konferencja jałtańska",
        "note": "Luty. Wielka Trójka przesądza o podziale Europy; Polska w strefie ZSRR.",
        "core": false
      },
      {
        "year": 1945,
        "title": "Koniec II wojny światowej",
        "note": "8 maja. Polska traci ziemie wschodnie i suwerenność.",
        "core": true
      }
    ]
  },
  {
    "year": 1989,
    "title": "Upadek komunizmu",
    "role": "Wolność",
    "note": "Obrady Okrągłego Stołu i pierwsze częściowo wolne wybory 4 czerwca. Tadeusz Mazowiecki zostaje pierwszym niekomunistycznym premierem.",
    "hooks": [
      "Najłatwiejszy blok, bo każda data jest skutkiem poprzedniej: 1978 papież - 1980 Solidarność - 1981 stan wojenny - 1989 wolność.",
      "Nobliści powojenni: 1980 Miłosz, 1983 Wałęsa (pokojowy), 1996 Szymborska, 2018 Tokarczuk.",
      "Wejście na Zachód: 1999 NATO, 2004 Unia Europejska - pięć lat różnicy."
    ],
    "events": [
      {
        "year": 1947,
        "title": "Sfałszowane wybory",
        "note": "Komuniści przejmują pełnię władzy; początek okresu PRL.",
        "core": false
      },
      {
        "year": 1956,
        "title": "Poznański Czerwiec",
        "note": "Pierwszy masowy protest robotniczy w PRL, krwawo stłumiony.",
        "core": true
      },
      {
        "year": 1966,
        "title": "Milenium chrztu Polski",
        "note": "Tysiąclecie chrztu; władze komunistyczne organizują konkurencyjne obchody.",
        "core": false
      },
      {
        "year": 1968,
        "title": "Marzec '68",
        "note": "Protesty studenckie i antysemicka kampania władz; emigracja tysięcy Polaków.",
        "core": false
      },
      {
        "year": 1970,
        "title": "Grudzień '70",
        "note": "Masakra robotników na Wybrzeżu; upamiętnia ją pomnik Trzech Krzyży w Gdańsku.",
        "core": true
      },
      {
        "year": 1978,
        "title": "Karol Wojtyła papieżem",
        "note": "16 października. Pierwszy polski papież, Jan Paweł II.",
        "core": true
      },
      {
        "year": 1979,
        "title": "Pierwsza pielgrzymka Jana Pawła II",
        "note": "\"Niech zstąpi Duch Twój i odnowi oblicze ziemi, tej ziemi\".",
        "core": true
      },
      {
        "year": 1980,
        "title": "Powstanie \"Solidarności\"",
        "note": "Strajki w Stoczni Gdańskiej, porozumienia sierpniowe, na czele Lech Wałęsa.",
        "core": true
      },
      {
        "year": 1980,
        "title": "Nobel dla Czesława Miłosza",
        "note": "Nagroda z literatury dla poety na emigracji.",
        "core": true
      },
      {
        "year": 1981,
        "title": "Stan wojenny",
        "note": "Wprowadzony 13 grudnia przez gen. Wojciecha Jaruzelskiego.",
        "core": true
      },
      {
        "year": 1983,
        "title": "Pokojowy Nobel dla Lecha Wałęsy",
        "note": "Nagroda dla przywódcy \"Solidarności\".",
        "core": true
      },
      {
        "year": 1984,
        "title": "Zabójstwo ks. Jerzego Popiełuszki",
        "note": "Kapelan \"Solidarności\" zamordowany przez Służbę Bezpieczeństwa; dziś błogosławiony.",
        "core": true
      },
      {
        "year": 1989,
        "title": "Okrągły Stół i wybory 4 czerwca",
        "note": "Upadek komunizmu; Tadeusz Mazowiecki pierwszym niekomunistycznym premierem.",
        "core": true
      },
      {
        "year": 1990,
        "title": "Lech Wałęsa prezydentem",
        "note": "Pierwszy prezydent wybrany w wyborach powszechnych po 1989 r.",
        "core": true
      },
      {
        "year": 1996,
        "title": "Nobel dla Wisławy Szymborskiej",
        "note": "Nagroda z literatury.",
        "core": true
      },
      {
        "year": 1997,
        "title": "Konstytucja RP",
        "note": "Uchwalona 2 kwietnia, obowiązuje do dziś.",
        "core": true
      },
      {
        "year": 1999,
        "title": "Wstąpienie do NATO",
        "note": "Polska wchodzi do sojuszu północnoatlantyckiego.",
        "core": true
      },
      {
        "year": 2004,
        "title": "Wstąpienie do Unii Europejskiej",
        "note": "1 maja, razem z dziewięcioma innymi państwami.",
        "core": true
      },
      {
        "year": 2005,
        "title": "Śmierć Jana Pawła II",
        "note": "2 kwietnia. Żałoba narodowa w całej Polsce.",
        "core": true
      },
      {
        "year": 2010,
        "title": "Katastrofa smoleńska",
        "note": "10 kwietnia. Ginie prezydent Lech Kaczyński i 95 innych osób.",
        "core": true
      },
      {
        "year": 2018,
        "title": "Nobel dla Olgi Tokarczuk",
        "note": "Nagroda z literatury za rok 2018.",
        "core": true
      }
    ]
  }
];
